project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - whitebelt.qmd
      - about.qmd 
      - drills.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



