---
title: "Arm Bar Focus"
---

# Background 

In November/December 2025 we've been working on an armbar focus. Here I'll document all the versions Tim has been showing us (these are not all the armbars of course!)

## Armbar from scissor sweep 

- This is for when you go for a scissor sweep, but they defend by sitting back as you do so, **and you have their arm still**
- This won't come up very often, but it's worth knowing about
- Feet on hips, you have grips
- They come forward
- As if you were going for a scissor sweep, slide your left foot down past their knee as if you were using it as a lever (it will help you move yourself)
- Right foot also slides backwards after you feel them move back
- Keep the arm! 
- Now use your legs to move yourself as close to 90 degrees as you can
- As you move round, right leg comes up onto their back, pulling down
- Left leg swings over their head, keeping heel down & toes up
- Now finish the armbar in the classic way - grip wrist, keep their thumb up, squeeze knees, lift hips in line with your knees. 

## Classic armbar from guard

- This is for when you have your grips, you have them in guard, and they're just starting to get posture 
- If they're already all the way up, it's too late 
- As they start to come up, bump upwards with your hips and pull the arm you're gripping across your hips
- Legs: Left foot goes to their hip, right foot hooks across their back 
- Try to get this as far up and across the back as you can **before** you turn 
- Now use your foot and knee to pull yourself around to 90 degrees
- **Hang onto their arm!**
- As soon as you can, swing your left leg over their head, pulling down with your knee and foot (don't kick them in the head as you do this!)
- Hands come up to the wrist, their thumb is up, finish the armbar
- Don't forget to keep your shoulders rounded 

## Spinning armbar from knee ride

- We've done this one before! 
- You're in knee ride and the person you're pinning makes a mistake - goes to push your knee away
- Now they have their arm in a chicken wing! You can scoop that up and pull it towards you
- Pull your elbow towards your hip 
- Now put your other (left) hand on the floor behind their back, a fair way down (near their belt) to give you room 
- Now step your left foot AROUND their head - do NOT kick them in the head - and try to land as close to their armpit as you can 
- Now spin around so that you are sitting on the floor, still holding their arm, with your bum as close to their armpit as possible, hanging onto their arm and bringing your other hand to their wrist 
- Your right leg is now over their head and you are in the right position to finish the armbar
- [Here is a good demo of this technique](https://www.youtube.com/watch?v=ID3UY0tQkrM#ddg-play)

## Side control variation of spinning armbar

- This is for when you're in side control and the opportunity presents itself 
- This works when your opponent has hidden their arm around your neck
- Grab inside their elbow and pull the arm down, similar to previous versions 
- Walk your knees a little back away from them 
- Use your grip on their arm to roll them onto their side
- Now step over around their head as before 
- Finish the armbar 

## North-south variation of spinning armbar

## How to deal with being stacked in one of these

## Self-defence armbar from mount 

## Self-defence armbar from guard
