---
title: "Butterfly Guard Passes"
---

# Background

This section came about because we were doing no-gi focus in Jan/Feb 2024. Butterfly guard is central to a lot of the no-gi game and, even though we don't use it extensively in white belt, it's useful to know some of the basic passes and defences. 

## Turning it into normal guard-passing 

### Shoulder push

- To tip a person onto their back so that you can pass the guard as normal, the first method is to push on their shoulders

- Approach: **bend the knees**, dominant foot forward, back foot parallel with the heel slightly raised to spring forwards 

- Push firmly on their shoulders, tipping them onto their back 

### Heel tip

- For this one, grasp their heels and lift upwards to unbalance them onto their back 

- Approach as above 

## Spearing pass 

- This is for where you end up with your hands on their knees 

- Approach as above 

- Crouch **low**, hands on knees, your head connects with one of their shoulders (doesn't matter which)

- Legs are spread wide and bracing you

- You move around into side control on the same side as your head, using your head as a hand to push them down 

- As you do this, look where you're going (not into the person)

- If they want to not get screwed up, they should fall back onto their back

- Keep your head near their shoulder 

- Hand goes under their head, other hand controls their elbow as you move into side control 

- If they are fast enough to go for an underhook, hide your hand (the one that's not under their head)

## Folding pass 

- Sometimes the opponent will respond by going into defensive butterfly (one hand bracing them, maybe a hand on your head or neck)

- In this case, it's likely that one of their knees will be less balanced than the other 

- You may be able to push their knees sideways to fold them over 

- As you do this, move round into side control as above 

- Be careful not to head-butt them 

- This will end up with you being lower down than you'd like for side control, so you need to adjust upwards quickly 

- As you do this, make sure that, again, one hand goes under the head and the other controls the elbow 

- Make sure one knee goes to the **hip** and the other behind you, lowering your butt down to put more weight on the opponent. 

- See variation above