---
title: "Drills and Games"
---

## Solo turtle drill 

- Start in turtle position, forehead on floor, arms protecting head
- Move one arm outwards, placing palm on the floor, elbow up
- Sit through to the side opposite that arm, rotating through 90 degrees (if you had an opponent, you would now be facing into them). 
- You are now more or less in butterfly guard 
- Make sure your feet are tucked in properly so that your hands can guard them (not feet together)
- Now tuck one knee close to your body (the opposite knee to the arm you just used)
- Push yourself upwards with a hip thrust so that you are now on one knee and one foot
- Move back into turtle position and start again (going the other way, back to the direction you started in)
- This is good for core strength and can be done in a small space


## Grip fighting drill (no-gi)

- We learned this drill in January 2024 (week 3 of training)
- One participant sits in butterfly guard (knees apart and bent, feet somewhat towards your body, core engaged, back curved)
- Participant 2 is standing with right foot forward, ready to drive forward from the ball of the back foot
- The aim of the game for standing participant is to do one of 3 things: 
  - Push sitting participant over with a quick shove to the shoulders (must be firm)
  - Tip sitting participant over by grabbing their heels and lifting
  - Place pressure on sitting participant's knees
- The aim of the game for the sitting participant is to do one of 3 things: 
  - Grab both wrists of standing participant: either under, over, or one of each (depending on position)
  - Grab one wrist of standing participant with both hands (baseball bat grip)
  - Grab one wrist and the same upper arm in a bent position (this is the strongest position)

- Can move from one position to another
- Do not CHEAT as standing participant by hiding your hands (sitting participant could then grab your feet/ankles)

## Push-pull drill from butterfly guard 

- This follows on from the previous game 
- This is more a drill than a game 
- Start from the point where you have a double-wrist grip from butterfly
- It doesn't have to be a double-wrist grip! Single-wrist will work! 
- Bottom person pulls on the standing person's wrists
- Standing person reacts by stepping forward, crouching down somewhat

### Pull - Idiot Sweep

- This works when the standing person then reacts by pulling back
- From butterfly, hook the standing person's ankles with your feet 
- Don't sit back
- Keep the feet active, in contact with their heels 
- Then push on their knees (use body, not just arms)
- Standing person will fall backwards

### Push 

- This works when standing person does not pull back
- Keep hold of their right wrist; with your left hand, grab their upper right leg
- Pull yourself under their hips (do NOT fall backwards yet)
- Let go of the wrist
- Hook your left foot up behind their right leg, up around their hip
- To do this you have gone onto your back and lifted your hips upwards
- Twisting around somewhat, pinch their leg between yours (your right leg is at the front)
- Grab your left butt cheek around their ankle to squeeze the leg in
- To sweep them, lift and twist sideways 
- Need core strength for this! Do the drill! 

### Exercise (to strengthen for this)

- Lie on your back with your legs elevated about 90 degrees, hands on ground at side
- Reach your feet up towards the ceiling, lifting your hips up from the ground
- Do this at least 15 times 
- Repeat 2-4 times a day
- Variation: Try pushing up as if moving into single-leg X (both sides)
- Variation: Without hands on ground, lift hips and rotate sideways. Keep doing this round 360 degrees

### Follow-up to pull

- In the event that your standing opponent resists your push and steps over your ankle hook: 
- Grab the heel of their foot (the one that has stepped over) and lift it 
- If they fall over, great! 
- Otherwise, react to what they do:
  - Maybe move straight into single-leg X? 
  - Otherwise, stand up and keep hold of the foot 


## Moving around in butterfly guard drill 

- The great strength of butterfly is the flexibility it gives you to move 
- Practice moving around from butterfly
  - With one hand behind you, the other between you and your imaginary opponent, move around 
  - Move around with fists on floor, but keep leaning forwards
  - "Levitate" by moving forwards or around without using hands at all 
  
## No-gi butterfly guard game against kneeling opponent 

- From butterfly, hook your feet under their knees 
- Must be close enough to guard your feet with your hands
- Grab their wrist and under their arm at the top (same arm - bent)
- Put your opposite foot (usually R) on their knee
- Pull them forwards so that they fall over your knee
- TBC

## "Dance pass" drill

- Your opponent starts on their back with their knees into their chest, in defensive pose
- You are standing, right foot forward, knees bent, ready to pass
- Leaning slightly forward but staying balanced, put your hands on your opponent's shins, putting your weight into it so they can't just free their legs

### Simple "dance pass"

- Step your left foot outward, swing the right one slightly back (to avoid getting caught on their foot) and bring it round near their hip, then step the left foot forward, ready to move into knee ride (or similar)
- This can also be done the other way round - less need to swing back with left foot since it's already back
- One, two, three
- Be precise with foot placement
- This is the only one you really need to know for white belt 

### Leg feints

- Version 1: Move their legs in the same direction you are stepping: left - right - left and then throw aside as you go into the pass - so this is still 1 - 2 - 3

- Version 2: Move legs first, THEN step, so 1 - 2 - 3 - 4. Don't think too hard about this one or you'll get screwed up

- Version 3: Move legs back and forth instead of left and right. 

- Version 4: If they push up to try and put their legs on your hips, you can do the classic bullfighter's pass - push against them slightly then fling the legs aside like a bullfighter's cape as you pass. 




