---
title: "Self Defence"
---

# Background 

Here I will document some rudimentary systems for self defence that Tim is showing us

## Head lock escapes 

- It isn't usual in BJJ for someone to have you in a head lock, but it's a common situation in self defence 

- Fortunately it's not hard to escape them! 

### If they haven't got you bent over too much 

- Grab both their forearms to pull them away from your neck 
- Walk your legs forwards with bent knees until you are underneath your own shoulders
- Now essentially do a single-leg takedown - step forwads, grab their leg, lift and spin

### If they've got you bent right over

- Whoops! But don't panic
- Again, grab both forearms 
- However, instead of walking under, now shoot your left leg forwards so that you slide into a sitting position 
- As you do this, roll them over you - it should feel quite easy, but careful of getting your arm squished

## Bear hug escapes and sweeps

### If they grab you over your arms 

- Great! This puts you in a better position to start with. 
- First drop down lower, bending your knees, pushing your elbows outwards
- Now shoot your arms around their waist, grabbing your hands together in a gable grip if you can
- Pull them towards you to bring their hips forward 
- Push your arms upwards towards their shoulders, elbows out, pushing their arms up and hopefully breaking their grip
- Pivot on your left foot, left hand comes up to their shoulder in an underhook, right hand on their bicep, elbows in & grip tight, head against their chest 
- This should be robust to them pushing, pulling, or trying to headlock you. Keep your hips under your shoulders, right foot back, strong posture. Keep pressure on your head. 

### If they grab you under your arms 

- Start is the same as above. Drop down into a squat. 
- As you do this, pivot and swim your right hand in under their arm
- Then wedge your left hand as far in as it will go. Your head is now against their chest. 
- Quickly step back with your left foot, pulling your head back, and use the space to insert your left hand, stepping back again once it's in
- Shoot your hands behind their back and gable grip. Pull them in as above. 
- Hands move up under their armpits as above
- Swing into the underhook as above. 

### Next moves: 1. Near-leg single-leg takedown 

- This is the one to use if they have one leg forward and it's the one closest to you 
- Step forwards, bending your knees, and quickly grab the leg with both hands in a gable grip 
- Pull the leg past your hip 
- Now grab their waist with your left hand
- Step outwards with your right foot and pivot, throwing them to the ground. 

### Knee-block high-5 running sweep 

- I don't know what else to call this one! 
- This is when it's the leg furthest away from you that is forward 
- Block their knee with the outside hand (at this stage, it's your right hand)
- At the same time, high-5 over their shoulder with your other hand (left) **in the direction you want them to fall**
- As you do this, spring off your back foot and run in the direction of your high-5 as if you were sprinting off the starting blocks. Don't be hesitant! 
- This should cause them to fall to the ground easily. 

### Duck-under to knee & ankle sweep 

- This is the safest to do if they are giving you some headlock energy
- Duck under the head-locking arm to their back & grab round their waist in a gable grip
- If they are leaning slightly forward, drop down and cup their knee with the hand **away** from where you're looking and their ankle with the hand below where you're looking
- Push forward with your shoulder but don't let go of the knee & ankle! 

### Duck-under to chair sit sweep 

- As above, if they are giving you the headlock energy, duck under and grab their waist
- If they are leaning slightly back, step sideways with your right foot and pivot on that foot
- As you pivot, drop into a sumo squat 
- Keeping your grip, drop them onto the floor. You're not actually sitting in this one. 
- Push down with your hands and move away (for self defence)

### Stuff and lever

- This is the one to do if they look like they are going low to rugby tackle you
- As they go down initially, go with them, keeping your grips 
- If they persist, going lower, change your grip to on top of their head
- You don't need to push hard. It's mainly keeping hold of their arm
- Push their head through as you hang onto their arm, step forward with your right foot and pivot, bending your knees so that they fall over
- You should not have to push hard on the head - the main thing is to hang onto their arm as you pivot. This may take some practice. 

## Bear hug from behind

- This is pretty simple and not dissimilar to above
- Insert your thumbs inside their hands from above and push down with both hands
- Drop down into a crouching position
- Now step forwards, but push back with your shoulders, pushing your hips forward
- This should break their grip. Keeping hold of their wrist, spin around, under their arm, and quickly move into a position where you are holding them from behind
- Now you can do a knee & ankle or other suitable takedown. 
