---
title: "Systems"
---

# Background 

Here I will document some rudimentary systems for attacks and sweeps that Tim is showing us

## Attacks from closed guard

- First, get your grips. Right hand goes into their sleeve in a pistol grip, thumb inside 
- Left hand reaches across under their arm, grabbing the seam so you have a good hold
- While you're doing this, keep them down firmly with your knees! 
- Lift your hips quickly to jolt them
- As you do this, pull their arm firmly with your right hand to try and get it across your hips

### Arm bar 

- Use this one when you can get their arm straight across your hips 
- Lift your hips again and swing your left leg up over their shoulder as you move your body to the right 
- You can use your other leg against them as leverage
- Quickly cross your ankles again if you can
- Now you can let go of their armpit and push their head down under your leg as you shift your body a bit further across 
- Bring your hands both to their wrist, grasping wrist to your chest, pulling their arm straight
- Your thumbs are pointing up
- Left leg scissors down over their head so it's grasping the head, knee points up 
- Now lift your hips in the direction your knee is pointing, UP. Do NOT ease pressure on the wrist 
- You should get a tap quite easily. If not, have you eased the wrist? 

### Flower sweep

- Use this one when you DON'T get the arm all the way across AND they move forward and put their weight on you (e.g. their hand on your bicep)
- Keeping your grip on their armpit, let go the sleeve and reach around with your right hand to grab their gi at the knee 
- Put your left foot on the floor. Use this to push your body around to the right.
- Kick your right leg upwards towards the ceiling, sweeping them over as you do this so that you land in mount 
- Ben says this is the best sweep to try on your lover! It is quite fun. 
- [This is a reasonable approximation of this sweep](https://jiujitsulegacy.com/videos/how-to-flower-sweep-from-closed-guard/), although with slightly different grips. 

### Cross-collar choke 

- Use this one where they don't do anything after you get your grips
- OK, you wanna be choked then! 
- Reach up with your right hand and get a REALLY good grip on their gi, as far up as you can go behind their neck 
- Now move your body and arm slightly to the right, forcing their neck upwards so you can reach under with your left hand
- Get a really good grip with your left hand as far up as you can go on the other side of their collar
- Now turn your palms UPWARDS, forcing your thumb-knuckles into their neck 
- Now pull your elbows DOWN towards the ground (as if they can go through the ground), crunching up slightly but not too much (it's mainly about bringing the elbows down, keeping them IN)
- You should get a tap quite quickly

## Attacks from knee ride

### Far knee (spinning arm bar)

- This one works when you're in knee ride, and your opponent leaves the neck-protecting position to push on your knee with the hand that is furthest from the side you are on 
- Aha! You have an arm! Grab their tricep and pull towards you 
- Now place your other hand on the floor on the far side, far enough down their body that you can spin there
- Sliding your hand up towards the wrist, pivot around so that you land under their armpit on the far side, as close to their body as you can manage
- You should be in a position with your foot under their armpit 
- If you fall backward, let your arm go outward to avoid breaking their arm! 
- Now sit up again and grab their wrist with both hands
- Keeping knees pinched together, lean slowly backwards until you get the tap, lifting hips if necessary

- [Here is a good video of this technique](https://youtu.be/ID3UY0tQkrM)

### Close knee

### Cross-collar choke

## Head lock escapes 

- It isn't usual in jiu jitsu for someone to have you in a head lock, but it's a common situation in self defence 

- Fortunately it's not hard to escape them! 

### If they haven't got you bent over too much 

- Grab both their forearms to pull them away from your neck 
- Walk your legs forwards with bent knees until you are underneath your own shoulders
- Now essentially do a single-leg takedown - step forwads, grab their leg, lift and spin

### If they've got you bent right over

- Whoops! But don't panic
- Again, grab both forearms 
- However, instead of walking under, now shoot your left leg forwards so that you slide into a sitting position 
- As you do this, roll them over you - it should feel quite easy, but careful of getting your arm squished

## Feet on hips 

### Double ankle sweep 

- This one works when you have your feet on their hips, you have good grips, and they are standing with both feet close to your body, and they lean their weight backwards away from you. 
- Reach out and grab both their ankles firmly, then push them backwards with your feet. 
- They should fall onto their butt. Keep hold of their ankles. 
- Move your feet so that they are inside their hips
- Pick a side and turn slightly onto that side, placing your far foot on the ground near their butt with your knee upwards
- Push up onto your elbow and move your other foot UNDER that foot, then stand up
- Don't let go of their ankles! This will prevent them standing up
- You are now ready to pass into knee ride and/or mount. 

### Tripod sweep 

- This is very similar to the above, but works when they are in a staggered stance, so you can't grab both ankles. You can check by looking through your legs or over your shoulder. 
- Weight still has to be back 
- One ankle is enough! 
- Release your grip on the collar, grab the ankle, and hook your foot round the opposite knee
- With the foot that is on the hip above the ankle you have grabbed, push outwards and sideways to sweep the person. 
- They should fall onto their butt. *Keep hold of their ankle*. 
- Move your feet so that they are inside their hips
- Pick a side and turn slightly onto that side, placing your far foot on the ground near their butt with your knee upwards
- Push up onto your elbow and move your other foot UNDER that foot, then stand up
- *Don't let go of their ankle*! This will prevent them standing up
- You are now ready to pass into knee ride and/or mount.

### Triangle choke 

- This one works when their weight is forward, their head is lined up with yours, and you have an arm
- Pull the arm sideways (straight) so they can't brace on you 
- If they are trying to push forwards to squish your knees towards you, try putting a foot on a shoulder to push them back 
- Don't push too far away from yourself! Keep knees above hips
- Now lift your butt and hook the right foot (that was maybe on their shoulder) over their shoulder
- Keep your grips for now! 
- Swivel your body to the right so that your head is away from theirs, and as you do this, your right foot should come around across their neck 
- Keep this foot down!! 
- Now hook your other knee over your shin. Needs to be *knee* not ankle! Otherwise you won't get the choke!
- Try not to lift the other foot as you attempt this. You may need to swing your leg outwards a little. 
- Now you are in a good position to do the triangle choke. (You have maybe let go of the lapel at this stage)
- Squeeze your knees together until you get the tap 

### Omoplata 

- This one works when their weight is forward, you have their arm, and their head is OFF alignment with yours on the side away from their arm
- With the leg that's on the opposite side to their head, kick upwards under their armpit, enfolding their shoulder and folding them over
- As you do this, you should be able to sit up with the momentum of your leg 
- Now you're sitting up and you have their shoulder 
- Scoot around in a circle till you're aligned with their body (TIGHT circle)
- Lean forwards to flatten them out (I'm a bit hazy on this bit)

- [Here is the closest video I've been able to find of this version](https://www.youtube.com/watch?v=0Vd2OGXHkso&ab_channel=BlackDragonBJJ%2FCobraKaiKarateDungannon)

### Arm bar

- This one works when their weight is forward, you have their arm, and their head is OFF alignment with yours **on the same side as their arm**
- This won't happen very often on its own but may be a reaction to something else 
- First lift your right leg up (the one on the same side as their arm) onto their back as if rock climbing up - your hips are now off the ground
- This will have turned your body a little already 
- Now turn your body further and lift the other leg over their head, clamping down over their neck, heels down, toes up
- You now have their arm in the classic arm bar position
- Move hands to their wrist (at least one hand needs to be touching the top of their hand) and extend the arm a little
- Pinch knees together and slowly lift hips to finish the arm bar
- Be sure to pay attention to the angle - move upwards towards you knee
- **Side note** if they try to stack you, there are some things you can do 
  - Don't let them - lock your knee in place
  - You can shoulder walk back till your knee is at right angles again 
  - If they're really stacking you, you can reach your right hand across to the **opposite** foot and grab it, then pull yourself underneath them - as they unbalance, you will land in the classic mount arm bar

