---
title: "White Belt"
---

# Things we need to know for White Belt

## Closed guard - top - 4 passes 

- First, get posture: starting with head on opponent's chest, place hands on their biceps, then move your hands downwards to place pressure on their lower ribs while working your way to an upright sitting posture. Elbows IN. 
- Then move hands down to floating rib, elbows move to inner thighs. 
- Make sure your CORE is firm - belly button to spine - to prevent being pulled back down. 
- Step outwards with the left leg - remember to have leg as far back as possible to prevent opponent grabbing your ankle 
- If their ankles are still locked, push on their knee to break the grip 

### Over-leg pass

- As soon as grip is broken, grab their legs in an under/over grip 
- Remember to slouch down while doing this
- Elbow IN! 
- "Turn the wheel" to turn their hips
- Pull their leg UNDER your left knee (do NOT lift your knee over!) - keep pressure on their leg
- Lead with the hand - move your left hand under their head, while right hand moves to control their elbow
- As you do this, you move the rest of your body into side control position - right knee to the hip, left leg extended

### Under-leg pass 

- Only use this pass if your opponent resists, such than their leg does not hit the floor 
- Shrug your shoulders (remember to slouch!) so that your shoulder is now under their leg 
- Right knee moves forward next to their hip 
- Reach forward to grab their gi (for no-gi, grab their shoulder if you can)
- Keeping your weight LOW and your head close to their shoulder, move around into side control position 
- Do NOT lift your head! 
- Keep the pressure down towards the hip until their leg slips over your head
- Hands move into side control position - under head, controlling elbow. 
- [This link is the closest I've found to a reasonable illustration of this pass.](https://www.ultimatejujitsu.com/learn-jujitsu-techniques/brazilian-jiu-jitsu-techniques/escapes/passing-the-guard/)

### Double under-leg pass 

- This is useful if both over- and under-leg passes have been successfully resisted (e.g. opponent is pinching their legs together)
- Grab both legs in an under-hook grip 
- If you can, grasp your hands together low around their hips (if not, you can do this later in the pass)
- Now walk you knees forwards until their bum is level with your belly button (keeping the grip or fixing it now)
- Once you are in this position, pick a shoulder. Push your head downward towards this shoulder, reaching with the opposite hand (grab the gi lapel, or shoulder for no-gi)
- Now take two steps sideways to move around their body. Keep your head close to their shoulder as you do this, keeping the pressure on. 
- As in the single-under pass, eventually their leg will pop over your head (do NOT lift your head or take pressure off)
- At this point, correct your posture and move around into side control - again, hand under head, other hand controls elbow. 

### "Dancing" pass 

- This one is sometimes called the "toureando/toreada" pass 
- This should be used if the opponent places their feet on the ground, or has the legs up between you in a defensive posture
- If both feet are on the ground, place your hands on their knees and use this pressure to jump quickly up to your feet (knees bent), keeping close to their body
- If knees are up, instead place your hands on their shins and use the downward pressure to spring upwards while controlling their legs 
- Skip your left leg around their knee, then quickly follow with your right leg, moving smoothly to the knee ride position - 1-2-3. 

## Guard - bottom - two sweeps, two submissions

### Scissor sweep

- You have the opponent in your closed guard, and they either haven't sat up yet or you have pulled them back down with your legs (e.g. after knocking their hands away)
- This sweep is preferred in gi, less so in no-gi because the timing is more critical 
- Grab their gi lapel (or, in no-gi, the back of their head)
- As you do this, place your left foot on the ground, right leg between you, shrimp sideways, and pull them forward so that their weight is balanced on your shin
- Once they are in this position, scissor your legs quickly so that they topple over to one side. 
- As they do this, your weight follows theirs (keep your grips!) so that you easily roll over into mount 
- Make sure to finish in the correct mount position with your hands on the floor.
- [This is the best approximation I have found of an illustration of the scissor sweep](https://www.ultimatejujitsu.com/learn-jujitsu-techniques/brazilian-jiu-jitsu-techniques/transitions/scissor-sweep/)

### Hip bump sweep

- This one is used when your opponent is sitting up and perhaps leaning backwards a bit to avoid being pulled forwards by you 
- From the bottom guard position, reach one hand over the opposite shoulder (you need to be able to do this on both sides), and sit up into the opponent's lap. As you do this, bump them with your hip so that they fall backwards into your mount
- Make sure to finish in mount position properly with your hands on the floor. 

### Arm bar

- Your opponent has their hands on your shoulders 
- You grab their right arm just above the elbow with your right hand and push it across their body
- Push your left hand into their right shoulder just under their chin 
- Now quickly hoick your legs upwards so that you are gripping them around their shoulder (this is the bit I have trouble with)
- Next move??? 
- Left leg goes over their head
- Now you are at right angles to your opponent in the correct position to finish the arm bar 
- Hands move upwards to grip their wrist firmly
- This should be a very tight position but if necessary lift the hips to finish the submission

[This is the closest approximation I have been able to find of this move](https://www.ultimatejujitsu.com/learn-jujitsu-techniques/brazilian-jiu-jitsu-techniques/arm-locks/arm-bar-from-the-guard/)

### Kimura

- This one is to use when the person in top position puts their arm on the floor 
- Immediately grab the arm with a baseball bat grip (thumb encircles the arm)
- Put opposite foot on the floor, same knee on back, and crunch sideways, sitting up slightly and bringing the arm with you so that it bends over their back into the start of the Kimura 
- Reach other hand through to grab your own wrist into the Figure 4 
- Engage the wrist by pushing your top hand down slightly, then slowly push their wrist upwards towards their shoulder until they tap
- Go slowly here - don't want to cause injury. 


# Escapes - two for each position

## Half guard

- Your opponent has you in half guard (they have their legs round one of yours) because you did something dumb e.g. while trying to transition from side control to mount
- Don't worry! Move around into side control position anyway with the rest of your body.
- Ball of left foot extends out, right knee on floor, arms into position (under the head and controlling the elbow)
- Flatten your opponent
- Toes engaged! PIN their leg with your thighs
- Now switch legs; keeping your trapped (usually right) foot on the floor, move both arms over their body, left knee to hip. Push their knee out and down. 
- Top hand pushes their head out of alignment.
- Make sure you keep the weight on here - DON'T roll back onto your side. 
- Move your trapped foot heel/toe/heel/toe until you have enough room to *slice* the knee of your trapped leg down to the floor. Trap their arm too. Heavy on the knee. 
- Patience here! This may take time 
- Then smoosh their face with your upper body so they have to look away. This will feel awkward and they will likely let go 
- If you are still trapped, shift your weight so that you are properly on top of them and move your left foot across to hook their feet and unlock them. 
- Now you should move into mount position, sitting back with your weight on your opponent's hips

- *Version 2*: This is largely the same as the one above, but can be used if they are pinning your leg really tight and you can't do the heel-toe thing
- Move your right hand so it's pushing their leg a bit more outwards (so move it to the inside of their leg)
- Instead of heel-toe, use the balls of your feet to walk around towards side control position
- This will create a nice gap between their legs that you can just slice your knee through 
- You don't have to wait for their annkles to pop
- Now proceed as above

## Knee ride

- It is critical here to keep your **core engaged**. Don't panic! You know this escape! 
- Move your left knee upwards to push on your opponent's back
- Now bridge strongly on your other (right) foot, unbalancing your opponent 
- You can use both feet to bridge if you're quick
- As they fall, quickly shrimp out from under them, turning TOWARDS them onto your knees and grabbing their knee with your arms
- Your left foot goes UNDER your right leg as your right leg remains elevated in the bridge position during this manoeuvre. 
- Self-defence variation - you can shrimp and spin away

## Mount

### Bridge and roll 

- This is the simplest escape from mount but usually won't work against a seasoned opponent
- Grab their right arm with your right hand just above their elbow and bring it across their body 
- With your other (left) arm, reach across their back as far as you can so you have them in a bear hug
- Bridge strongly on your right foot and roll them over as they unbalance
- You should land in mount quite easily. Remember to finish the transition into mount

### Knee-in escape

- This is a more reliable escape if your opponent has a solid mount game
- First, establish the survival position by pushing your left arm down against their hips, bracing it with your right hand on your wrist
- Engage your core! 
- Left leg FLAT, right knee bent
- Bridge strongly on your right leg, keeping the ball of your right foot firmly on the floor an knee upright
- As you do this, bump outwards **strongly** with your right hip and shrimp outwards to escape
- If you do not keep your right foot engaged strongly with the floor this will fail 
- **Shrimp again** to create lots of space between you 
- Now right knee comes in between you and your opponent 
- Feet on hips, move your body around so that you are facing your opponent
- Create a push-pull to pull them into your guard
  - For gi play, you can grab their lapel and sleeve
  - For no-gi, do this by grabbing their wrist with both hands
- Once you have established this tension, quickly move your feet off their hips and pull them into your guard


## Side control 

### Knee-in escape 

- Side control survival: Make sure your forearms (at least your right one) are between you and your opponent. Brace and make sure core is firm
- If your arms aren't in, you should try to at least get the right one in. You can twist slightly away to do this
- Have right leg up against their hip to stop them moving into mount
- Bridge strongly and shrimp sideways
- Bring your knee in between yourself and opponent, over their leg (at their HIP)
- If you can't get it all the way in, **shrimp again**
- Make sure the knee meets your elbow
- Use the other leg to push against their side/back to push yourself round so you're parallel to them - *redirecting* them
- As you do this, your knee should come all the way across their hips
- Bring right foot out and up onto hip
- Turn to extract the other foot and bring it also onto the hip
- Gi - Grab their gi and bring them into guard with push-pull
- No-gi - grab their wrists and push-pull them into guard 


### Underhook escape 

- After making space, if you can get your right arm out under their arm, you can try the underhook escape
- High-five across their back as you pull yourself out from under them, while your left leg scissors across your right. 
- I'm a bit rusty on this one. 

## Back control 

- Step no. 1 - don't get choked - push their arm away, pulling it downwards
- Then start from the bottom
- First you need to get rid of the bottom hook (top one doesn't matter)
- Bridge in the direction you are facing (towards the corner of the room)
- **Walk yourself away** from them to lose the hook
- Then come down so that your butt is on their knee
- This should pin their leg and get rid of the hook
- Now turn so that your back is flat and push upwards a little so you're pinning their thigh
- **Variation 1** This is when their HEAD is on the same side as yours - so the head is blocking you
  - Push upwards and back till your head is on the floor 
  - Now work your inside elbow onto the floor 
  - Push with your back leg to spin towards them into their guard 
- **Variation 2** This is when their ARM is on the same side as your head - so the arm is blocking you
  - Force your head backwards so that it is pinning their arm underneath it - making it weak 
  - Pull downwards on their top arm. As it comes away, shift your grip so both hands are on it, pushing it away and down so it's almost straight
  - Now quickly duck your head under it, pushing the arm out of the way while keeping your grip on it 
  - Pushing the arm you're holding towards their belly, spin towards them into their guard (here you can push with your feet)
  - If you've done this correctly you should be able to keep hold of their arm, putting you in a good position to escape the guard. 

## Scarf hold 

- This is otherwise known as Kesa Gatame
- Not a super common position in grappling as it's hard to submit from, but worth knowing 
- There are two escapes, depending on your opponent's head position 

### Sit-through escape 

- This one works when their head is on the OTHER side from their leg on the floor (making it easier for them to hit you if this were self-defence)
- Step 1 self-defence: Don't get punched - right hand on their bicep, arm slightly bent to prevent the punch
- Step 1 grappling - don't get submitted - hide your arm by clasping hands behind their back
- Step 2: With your left hand, push their jaw firmly away from you, so that their body moves back. Make sure your fingers are pulled back to avoid bites or weirdness
- Take 3 steps away from them 
  - *Version 1* If they don't follow you, you'll feel their weight dropping off you
    - SHRIMP slightly onto your side
    - Now kick your legs outwards to swing yourself into a sitting position. 
    - You can now move into side control or top turtle depending on position.
  - *Version 2* If they DO follow you, you'll feel their weight continue to be on top of you 
    - Take 1 or 2 steps back TOWARDS them 
    - Reach back with your bottom hand (elbow on floor) and grab their leg (trouser leg OK)
    - You should now be able to lift their leg and tip them over, with you as the fulcrum. They should feel light.
    - If they avoid this by dropping their bum onto the floor, revert to version 1. 

### Sweep escape 

- There's probably a better word for this one but I haven't found it yet 
- This one works when their head is on the other side, close to their leg - this is a better pin, so more likely to occur in grappling 
- Step 1 self-defence: again, don't get punched - hold their bicep (remember don't use your thumb)
- Step 1 grappling: don't get submitted - hide your arm
- Step 2: turn onto your side, close to them
- Clasp your hands firmly around their back 
- Bridge towards them, and while still up, roll over on your shoulders, sweeping them over
- You should end up in a position to take back control or turtle
- For self-defence, push up and move away 

### Pull your head out 

- Extra escape if they resist the sweep by planting their feet firmly 
- Shrimp onto your side (CLOSE to them)
- Shrimp again to bring yourself up onto your knees 
- Pull your head out from under their arm till it pops out 

## North-south 

### Bridge, step & spin 

- Make sure your forearms are in the brace position - palms on forehead, elbows in, holding your opponent away from your body, head off the ground
- Bridge strongly upwards to one side to unbalance your opponent
- Step sideways away from the side they have fallen to 
- Spin away from them 180 degrees, landing in butterfly guard 
- Place feet on their hips and pull them into your guard 

### Wriggle escape 

- If they're heavy on top of you and you can't form your brace, try this one
- Push your arms as far up as you can, towards their hips - don't worry if you can't reach the hips yet
- Feet off the ground, walk your butt cheeks away from them
- If they follow you, you'll now be able to reach up and place hands on their hips
- Continue walking your butt away, pushing upwards with your arms till they're almost straight
- Now flip onto your front (kicking your legs out to help) and onto your knees, pulling back away from them

## Turtle

### Sit-through 

- This is for when the opponent is in side top turtle 
- Check to see if their knee is behind yours 
- If it is, you can sit through right away! 
- Put your left hand (assuming they are on your right) on the floor at right angles
- Quickly spin your body through the gap under your elbow and sit through to face your opponent 
- You can practice this staying as low as you can in case you're under a heavy opponent - it should still work. 

- *Variation 1*: If their knee is in front of yours: 
- Crawl forwards in an "echidna crawl" while still in turtle, trying to minimise the gap between elbow & knee
- When your knee is in front, sit through as above 

- *Variation 2*: If their knee is in front of yours, and they follow when you move
- Crawl forwards as above, but when you feel them following you, TURN THE CORNER
- As soon as you feel them left behind, sit through as above. 

### Spin-out 

- This is for when they are in *front quadrant* (in front of you)
- Windscreen-wipe your legs to one side (I prefer the right, but you should be able to do both sides)
- Step up with the outside leg 
- *Push* with that leg and move your head as if it's describing a 180 degree arc on the floor
- Your body should quickly spin out from under them, knocking into their arm
- You should end up facing them with your legs between - if possible, move into guard or push-pull into guard. 
- This move requires *confidence*. You can do it, even if they are heavy! 


